### ISSUE TITLE
Lien blank

### ISSUE THREAD

**Issue by Sandra-Louchart** [WildCodeSchool/orleans-php-202009-project-sophrologie#306]
J'aurais mis un lien blank sur votre page d'accueil sur ce lien "Certifiée au Répertoire Nationale de Certification Professionnelle (RNCP) Qualification reconnue par l’Etat"

**Comment by calouvts** [comment]
Tu peux m'expliquer ce que tu veux dire , il y a bien un lien sur ce sujet.

**Comment by calouvts** [comment]
traité
