### ISSUE TITLE
Compte

### ISSUE THREAD

**Issue by arnaudpilato** [WildCodeSchool/orleans-php-202009-project-sophrologie#314]
Quel est l'utilité de faire un compte si on peut rien en faire?

**Comment by KevinVanphavong** [comment]
leur connexion a leur compte permets de retrouver leur comptes rendus fait par la soprologue après chaque séances. Cela facilite le travail de la sophrologue au lieu d'envoyer mille mails. Tout est centralisé sur le site et le client pourra voir ses comptes rendues revenir dessus, car si c'etait par mail, c'est difficile a retrouver
