### ISSUE TITLE
Problème responsive page actualités

### ISSUE THREAD

**Issue by arnaudpilato** [WildCodeSchool/orleans-php-202009-project-sophrologie#321]
Padding trop important page actualité en responsive

**Comment by KevinVanphavong** [comment]
j'suis désolé mais tu vas devoir préciser a quelle section de la page ? car si on l'a pas fait avant c'est qu'on ne trouve pas qu'il en manque et si tu ne nous dit pas ou tu vois ça, on ne pourra rien faire.

**Comment by calouvts** [comment]
responsive admin traité globalement
