### ISSUE TITLE
Probléme d'ajout spécialités

### ISSUE THREAD

**Issue by BenjaminDbse** [WildCodeSchool/orleans-php-202009-project-sophrologie#322]
<p>savoir p&eacute;t&eacute;</p> affichés lors d'un ajout d'un spécialités dans le tableau admin/spécialite

**Comment by calouvts** [comment]
serait-il possible d'avoir une explication du problème car là je ne comprends pas le souci.

**Comment by KevinVanphavong** [comment]
mais il parle quelle langue ???

**Comment by calouvts** [comment]
Je pense avoir compris, c'est le balisage induit par le CKEditor dans le tableau? si oui correction faite
