### ISSUE TITLE
ajout modification de témoignages

### ISSUE THREAD

**Issue by BenjaminDbse** [WildCodeSchool/orleans-php-202009-project-sophrologie#336]
les champs sont obligatoires, les personnes ne veulent pas forcement mettre leur nom mais les champs sont obligatoires ça donne pas envie de laisser un commentaire

**Comment by calouvts** [comment]
Alors les témoignages ne seront pas saisis par les utilisateurs, seule notre administratrice les saisira sur la base de ce que ses patients lui feront remonter, elle positionnera de faux noms selon la demande du client.
